config/routes.rb
Rails.application.routes.draw do
  get 'gallery' => 'gallery#gallery'

  get 'contact' => 'contact#contact'

  get 'about_me' => 'about#about_me'

  root 'welcome#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about_me
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def gallery
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/about_me.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "M.P.", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Gallery", gallery_path %></li>
        <li><%= link_to "Contact Me", contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Maegen Portwood", about_me_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
    
  </div><!-- /.container-fluid -->

</nav>

app/views/contact/contact.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "M.P.", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Gallery", gallery_path %></li>
        <li><%= link_to "Contact Me", contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Maegen Portwood", about_me_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
    
  </div><!-- /.container-fluid -->

</nav>

<div class="bg2">

  <center>
    <div class="contactboxl">
      <span class="big">
      Dig my work?<br> Contact me! <br>My info is below.
      </span>
    </div>

    <div class="footer navbar-fixed-bottom">
      <div class="nofade">
      <%= image_tag ('insta.png'), class: "icon" %>
    <%= link_to "Instagram", "https://www.instagram.com/maegenportwood.art/", :target => "_blank" %>
    <%= image_tag ('fb.png'), class: "icon" %>

    <%= link_to "Facebook", "https://www.facebook.com/maegen.portwood", :target => "_blank" %>
    
    <%= image_tag ('Mail.png'), class: "icon" %>
    <%= mail_to "maegenportwood.art@gmail.com" do %>
    maegenportwood.art@gmail.com
    <% end %>
  </div>
    </div>
  </center>
<div class="bg">
  </div>
  </div>

    
 

app/views/gallery/gallery.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "M.P.", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Gallery", gallery_path %></li>
        <li><%= link_to "Contact Me", contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Maegen Portwood", about_me_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
    
  </div><!-- /.container-fluid -->

</nav>







<div class="container-fluid padtop">

<div class="row">
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("bodies2.JPG") %>
      <% end %>
  </div>
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("arm.JPG") %>
      <% end %>
  </div>
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("ash.JPG") %>
      <% end %>
  </div>
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("bird.JPG") %>
      <% end %>
  </div>
  
</div>

<div class="row">
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("hand1.JPG") %>
      <% end %>
  </div>
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("lipes.JPG") %>
      <% end %>
  </div>
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("peepole.JPG") %>
      <% end %>
  </div>
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("mixed.JPG") %>
      <% end %>
  </div>
  
</div>

<div class="row">
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("sunmoon.JPG") %>
      <% end %>
  </div>
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("phone.JPG") %>
      <% end %>
  </div>
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("twist2.JPG") %>
      <% end %>
  </div>
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("supermary.JPG") %>
      <% end %>
  </div>
</div>

<div class="row">
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("cowboy.JPG") %>
      <% end %>
  </div>
  
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("lyrics.JPG") %>
      <% end %>
  </div>
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("wgi.JPG") %>
      <% end %>
  </div>
  <div class="col-xs-6 col-md-3">
      <%= link_to contact_path, class: "thumbnail" do %>
      <%= image_tag ("bodies3.JPG") %>
      <% end %>
  </div>
  
</div>

















</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MaegenPortwoodArt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/home.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "M.P.", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Gallery", gallery_path %></li>
        <li><%= link_to "Contact Me", contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><div class="navbar-brand">Maegen Portwood</div></li>
      </ul>
    </div><!-- /.navbar-collapse -->
    
  </div><!-- /.container-fluid -->

</nav>

<div class="container-fluid">
	<div>
		
	</div>
</div>

<div class="container-fluid">

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
    <li data-target="#carousel-example-generic" data-slide-to="5"></li>
    <li data-target="#carousel-example-generic" data-slide-to="6"></li>
    <li data-target="#carousel-example-generic" data-slide-to="7"></li>
    <li data-target="#carousel-example-generic" data-slide-to="8"></li>
    <li data-target="#carousel-example-generic" data-slide-to="9"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag ("car1.JPG") %>
      <div class="carousel-caption">
        Some Tools!
      </div>
    </div>
    <div class="item">
      <%= image_tag ("car2.JPG") %>
      <div class="carousel-caption">
        Some Bluorange!
      </div>
    </div>
    <div class="item">
      <%= image_tag ("car3.JPG") %>
      <div class="carousel-caption">
        Some Paints!
      </div>
    </div>
    <div class="item">
      <%= image_tag ("car4.JPG") %>
      <div class="carousel-caption">
        Some Bluorange!
      </div>
    </div>
    <div class="item">
      <%= image_tag ("car5.JPG") %>
      <div class="carousel-caption">
        Some Bluorange!
      </div>
    </div>
    <div class="item">
      <%= image_tag ("car6.JPG") %>
      <div class="carousel-caption">
        Some Bluorange!
      </div>
    </div>
    <div class="item">
      <%= image_tag ("car7.JPG") %>
      <div class="carousel-caption">
        Some Bluorange!
      </div>
    </div>
    <div class="item">
      <%= image_tag ("car8.JPG") %>
      <div class="carousel-caption">
        Some Bluorange!
      </div>
    </div>
    <div class="item">
      <%= image_tag ("car9.JPG") %>
      <div class="carousel-caption">
        Some Bluorange!
      </div>
    </div>
    <div class="item">
      <%= image_tag ("car10.JPG") %>
      <div class="carousel-caption">
        Some Bluorange!
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="row">
  <div class="col-xs-6 col-md-3">
      <%= link_to about_me_path, class: "thumbnail" do %>
      <%= image_tag ("smile2.png") %>
      <% end %>
  </div>
  <p><span class="med">Welcome</span>, I’m Maegen Portwood the artist behind this page. Art is a form of communication for me and always has been. Through this communication I want to emote and connect with my viewer. This hasn’t always been my goal with art. I started out with a goal to draw then understanding light and shadows and learning to fully embrace the power of color. Now with my tool belt full, I hope that you can understand and see my goal. Please feel free to contact me with questions or just comments on the work. Please enjoy this page. 
Maegen Portwood 
  </p>
</div>





</div>